version: '3'
services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dolibarr
    networks:
      victim_network:
        ipv4_address: 10.254.249.201

  dilibarr_container:
    image: jnoahdevelop/dolibarr
    environment:
      DOLI_DB_HOST: mariadb
      DOLI_DB_USER: root
      DOLI_DB_PASSWORD: root
      DOLI_DB_NAME: dolibarr
      DOLI_ADMIN_LOGIN: admin
      DOLI_ADMIN_PASSWORD: admin
      DOLI_URL_ROOT: 'http://0.0.0.0'
      PHP_INI_DATE_TIMEZONE: 'Europe/Paris'
    ports:
      - "8080:80"
    links:
      - mariadb
    networks:
      victim_network:
        ipv4_address: 10.254.249.101

  dvwa_container:
    image: jnoahdevelop/dvwa
    command: tail -f /dev/null
    networks:
      victim_network:
        ipv4_address: 10.254.249.102

  telnetd_container:
    image: jnoahdevelop/telnetd
    networks:
      victim_network:
        ipv4_address: 10.254.249.103

  attack:
    image: jnoahdevelop/attack
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "6090:80"
    networks:
      victim_network:

  attack_sonsole:
    image: jnoahdevelop/attack_sonsole
    ports:
      - "6080:8080"
    networks:
      victim_network:

networks:
  victim_network:
    ipam:
      driver: default
      config:
        - subnet: 10.254.249.0/24

